name: "Filament Manager"
description: "Manage your 3D printer filament inventory with this Home Assistant add-on"
version: "1.0.0"
slug: "filament_manager"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
ingress: true
ingress_port: 5000
ingress_entry: index.html
ports:
  5000/tcp: null
homeassistant_api: false